default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456789
  host: localhost

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: myapp_production_user
  password: <%= ENV['123456789'] %>
